### ISSUE TITLE
not working on sony xperia 1 iii

### ISSUE THREAD

**Issue by legop3** [luisbocanegra/substratum-tweaks#1]
Hello, this may not be the right place to ask, but I need some help using this theme on my sony phone. 

I would like to:
- change the status bar height (I did get this to work)
- allow more than 4 notification icons in the status bar
- remove margins around notifications
- allow 3 or 4 columns of buttons in the quick access panel

please keep in mind that I have never used substratum before, 
should I be changing multiple settings for each "app" in the theme's setup menu, or should I be keeping them all together?

**Comment by luisbocanegra** [comment]
Hi @legop3,
Since I don't have a Sony device, I didn't try the Xperia software, but maybe you can help getting it to work.
> I would like to:
> - allow more than 4 notification icons in the status bar
> - remove margins around notifications
> - allow 3 or 4 columns of buttons in the quick access panel

Please note that some overlays may require you to reboot after enabling them to show the changes, if you are 100% sure they are not working it could be because:
1. They don't have them at their source
2. They use other names for those properties
3. It is encoded in the firmware

To further investigate I need you to upload Sony's SystemUI and framework-res apks to some cloud service and share the link here, I'll take a look at it when I have time.
> should I be changing multiple settings for each "app" in the theme's setup menu, or should I be keeping them all together?

If I understood correctly, yes you can enable multiple overlay types for the same app simultaneusly or have them separated, it should work both ways.

**Comment by legop3** [comment]
Thank you for the reply, I have gotten everything working that I wanted and your comment made me realize that rebooting my phone is what made it work, again thank you for your help and for this awesome piece of software.

:)

**Comment by legop3** [comment]
one thing that I couldnt get working at all is removing the notification icon limit from the status bar. I have an overlay that says "type1a: StatusBar Icons limit 10", I don't know if that's what the setting is supposed to do though.

**Comment by luisbocanegra** [comment]
> Thank you for the reply, I have gotten everything working that I wanted and your comment made me realize that rebooting my phone is what made it work, again thank you for your help and for this awesome piece of software.
> 
> :)

No problem I'm glad you found it useful.

**Comment by luisbocanegra** [comment]
> one thing that I couldnt get working at all is removing the notification icon limit from the status bar. I have an overlay that says "type1a: StatusBar Icons limit 10", I don't know if that's what the setting is supposed to do though.

It is supposed to allow having more notification icons in the Status Bar, it used to work in older Android versions. But now it seems to be limited in code to 5 or less icons due to notches and curved screens most probably. For example in LineageOS 19 (Android 12) I can set it from 1 to 5 and works, but higher gets ignored. 
By the way, forgot to ask, what android version do you have?

**Comment by legop3** [comment]
I am on android 12, Sony's stock rom, but rooted with magisk
